[workspace]
members = [
    "src/internet_identity",
    "src/canister_tests",
    "src/internet_identity_interface",
    "demos/selenium-test-app",
]

[profile.release]
debug = false # stripped by ic-cdk-optimizer anyway
lto = true
opt-level = 'z'
