version: "3.9"
services:
  ic:
    build: dfx-docker
    ports:
      - "8000:8000"
    volumes:
      - "./dfx-docker/canisters:/canisters:ro"
  nginx:
    build: reverse_proxy
    ports:
      - "8443:443"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
