[package]
name = "internet_identity_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7"
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
stable-structures = { git = "https://github.com/dfinity/ic", rev = "dc4d68663fc7d9c897602721ba59b9428dd238ef" }
