[package]
name = "canister_tests"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
base64 = "0.13.0"
flate2 = "1.0"
lazy_static = "1.4"
regex = "1.5.6"
serde = "1"
serde_cbor = "0.11"
serde_bytes = "0.11"
sha2 = "0.10"

internet_identity_interface = { path = "../internet_identity_interface" }

# All IC deps
candid = "0.7"
ic-cdk = "0.5"
sdk-ic-types = { version = "0.3", package = "ic-types" }
ic-interfaces = { git = "https://github.com/dfinity/ic", rev = "d0492fc0153edf16fa6f79675cf05bb99a2bd4ab" }
ic-types = { git = "https://github.com/dfinity/ic", rev = "d0492fc0153edf16fa6f79675cf05bb99a2bd4ab" }
ic-certified-vars = { git = "https://github.com/dfinity/ic", rev = "d0492fc0153edf16fa6f79675cf05bb99a2bd4ab" }
ic-crypto-internal-basic-sig-iccsa = { git = "https://github.com/dfinity/ic", rev = "d0492fc0153edf16fa6f79675cf05bb99a2bd4ab" }
ic-error-types = { git = "https://github.com/dfinity/ic", rev = "d0492fc0153edf16fa6f79675cf05bb99a2bd4ab" }
ic-state-machine-tests = { git = "https://github.com/dfinity/ic", rev = "d0492fc0153edf16fa6f79675cf05bb99a2bd4ab" }
